Online_Quiz/online_quiz/online_quiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quiz/', include('quiz.urls', namespace="quiz")),
]

Online_Quiz/online_quiz/quiz/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# ex: /polls/
	url(r'^$', views.index, name='index'),
	# ex: /polls/5/
	url(r'^detail$', views.detail, name='detail'),
	# ex: /polls/5/results/
	url(r'^results$', views.results, name='results'),
	# ex: /polls/5/vote/
	url(r'^score$', views.score, name='score'),
	url(r'^login$', views.login, name='login'),
	url(r'^addlogin$', views.addlogin, name='addlogin'),

]

Online_Quiz/online_quiz/quiz/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	id = models.AutoField(primary_key=True)
	question_text = models.CharField(max_length=200)
	#position = models.IntegerField()
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		#return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Answer_Choice(models.Model):
	id = models.AutoField(primary_key=True)
	question_id = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	correct_choice = models.BooleanField(default=False)

	def __str__(self):
		return self.choice_text
class Score(models.Model):
	id = models.AutoField(primary_key=True)
	username = models.CharField(max_length=200)
	score= models.IntegerField(default=0)

	def __str__(self):
		return self.username

Online_Quiz/online_quiz/online_quiz/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

class HomeView(generic.ListView):

	#model = Question
	template_name = 'home.html' 

	def get_queryset(self):
		pass

Online_Quiz/online_quiz/quiz/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.views import generic
from django.utils import timezone

#session
from importlib import import_module
from django.conf import settings
SessionStore = import_module(settings.SESSION_ENGINE).SessionStore
session = SessionStore()

from .models import Question, Answer_Choice, Score
import random

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]

	template = loader.get_template('polls/index.html')
	context = RequestContext(request, {
		'latest_question_list': latest_question_list,
	})
	return HttpResponse(template.render(context))
		

def detail(request):
	template = loader.get_template('quiz/detail.html')
	
	request.session['question_no'] +=1
	if request.session['question_no'] == 6:
		return HttpResponseRedirect(reverse('quiz:results'))
	key = random.randint(1,8)
	while True:
		i=0
		for value in request.session['question_list']:
			i+=1
			if value==key:
				key =random.randint(1,8)
				break
		if i == len(request.session['question_list']):
				break

	request.session['question_list'].append(key)
	#question = Question.objects.filter(pk=key)
	question = get_object_or_404(Question, pk=key)
	context = RequestContext(request, {
		'question': question,
		'question_no': request.session['question_no']
	})
	print question
	return HttpResponse(template.render(context))

		
def results(request):
	
	template = loader.get_template('quiz/results.html')
	
	#score = Score.objects.filter(id=request.session['user_id'])
	score = get_object_or_404(Score, pk=request.session['user_id'])
	context= RequestContext(request, {
		'score':score
	})
	return HttpResponse(template.render(context))

def login(request):
	template = loader.get_template('quiz/login.html') 
	context = RequestContext(request, {

	})
	return HttpResponse(template.render(context))

def score(request):
	#first
	#return HttpResponse("You're voting on question %s." % question_id)
	#p = Question.objects.filter(pk=2)
	user = get_object_or_404(Score, pk=request.session['user_id'])
	try:
		#selected_choice = p.answer_choice_set.get(choice_correct=request.POST['choice'])
		answer = str(request.POST['choice'])

	except :
	#except (KeyError, Choice.DoesNotExist):
		#Redisplay the question voting form.
		return render(request, 'quiz/detail.html', {
			'error_message': "You didn't select a choice",
			})
	else:
		
		#selected_choice.votes+=1
		if answer=='True':
			user.score += 1
			user.save()
		return HttpResponseRedirect(reverse('quiz:detail'))



		#selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
		
def addlogin(request):
	#p = Question.objects.get(pk=3)
	try:
		score = Score(username=request.POST['username'])
	except :
		return HttpResponseRedirect(reverse('quiz:login'))
	else:

		score.save()
		request.session['question_no'] = 0
		request.session['user_id'] = score.id
		request.session['question_list'] = []
		return HttpResponseRedirect(reverse('quiz:detail'))

	
	

Online_Quiz/online_quiz/quiz/templates/quiz/detail.html
{% extends "layout.html" %}

{% block content %}
<h1>Question: {{ question_no }}</h1>
<h2>{{ question.question_text }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quiz:score' %}" method="post">
{% csrf_token %}
{% for choice in question.answer_choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.correct_choice}}" />
	<label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label><br />
{% endfor %}
<input class="btn btn-default" type="submit" value="Submit" />
</form>
{% endblock %}

Online_Quiz/online_quiz/quiz/templates/quiz/index.html
{% extends "layout.html" %}

{% block content %}
	{% if latest_question_list %}
		<ol>
			{% for question in latest_question_list %}
				
				<li><a href="#">{{ question.question_text }}</a></li>
			{% endfor %}
		</ol>
	{% else %}
		<p>No polls are available</p>
	{% endif %}
{% endblock %}
		

Online_Quiz/online_quiz/quiz/templates/quiz/login.html
{% extends "layout.html" %}

{% block content %}
	<form action="{% url 'quiz:addlogin' %}" method="post">
	{% csrf_token %}
		<label for="username">Username</label>
		<input type="text" id="username" name="username" placeholder="Username"><br/>
	<input class="btn btn-default" type="submit" value="Login" />
	</form>
{% endblock %}

Online_Quiz/online_quiz/quiz/templates/quiz/results.html
{% extends "layout.html" %}

{% block content %}
<h1>{{ score.username }}</h1>
<h3>Score: {{ score.score }}</h3>

<a class="btn btn-default" href="{% url 'quiz:addlogin' %}">Take test again</a>
{% endblock %}

Online_Quiz/online_quiz/templates/home.html
{% extends "layout.html" %}

{% block content %}
	<h3>Welcome to the Python Online Quiz</h3>
	<p>This is the webiste for the online quiz of python. This website was created to test the ability of the python programmers from begineers to intermediate level.</p>

	<a class="btn btn-primary btl-lg" href="/quiz/login">Start Quiz &raquo;</a>
	
{% endblock %}

Online_Quiz/online_quiz/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>Python Quiz</title>
		<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/bootstrap.css' %}" />
		<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js' type='text/javascript'></script>
		<script src="{% static 'javascripts/bootstrap.js' %}" type="text/javascript"></script>
	</head>
	<body>
		<div class="container">
		{% block content %}
			
			
		{% endblock %}
		</div>
	</body>
	<footer>
		
	</footer>
	
</html>